name: Step Types
on: 
  workflow_dispatch 

jobs:

   say-hello-to-bash:
       runs-on: ubuntu-24.04
       steps:
          -run: echo "Hello Wrold"

   say-hello-using-shell:
       runs-on: ubuntu-24.04
       steps:
         - run : echo "Run the python command!"
         shell: python 

   say-using-actions:
       -uses:  actions/hello-world-javascript-action
       with : 
          who-to-greet: "anupam"
